const Engine=(()=>{
 const canvas=document.querySelector('#space'),ctx=canvas.getContext('2d');
 let w=innerWidth,h=innerHeight,active=false,ambient=true,paused=false,last=performance.now(),t=0,id='',d=0,duration=45,elapsed=0,objects=[],hits=0,errors=0,missed=0,rounds=0,score=0,goal=6,callback=null,inTime=0,phase='',phaseEnd=0,next=1,turn=0,spawn=0,sample=0,flips=[],pattern=[],inputIndex=0,pointer={x:-999,y:-999};
 const palette=['#76e4c7','#ffbf86','#b9a0ef','#9cd3ff'],glyphs=['✿','●','▲','◆','✚','★'],stars=Array.from({length:90},()=>({x:Math.random(),y:Math.random(),r:Math.random()*1.3+.3}));
 function resize(){w=innerWidth;h=innerHeight;const p=Math.min(devicePixelRatio,2);canvas.width=w*p;canvas.height=h*p;ctx.setTransform(p,0,0,p,0,0);if(active&&id!=='collect'&&id!=='follow'){pause(true);newRound()}}addEventListener('resize',resize);resize();
 const rnd=n=>Math.floor(Math.random()*n),shuffle=a=>{for(let i=a.length-1;i>0;i--){let j=rnd(i+1);[a[i],a[j]]=[a[j],a[i]]}return a};
 function project(o){const s=Math.min(w,h)*.9/(o.z||8);return{x:w/2+o.x*s,y:h*.54+o.y*s,s}}
 function layout(n,cols=3){const top=Math.max(205,h*.3),bottom=h-125,available=Math.max(125,bottom-top),cw=Math.min((w-60)/cols,150);return Array.from({length:n},(_,i)=>{const sx=w/2+(i%cols-(cols-1)/2)*cw,sy=top+(Math.floor(i/cols)+.5)*available/Math.ceil(n/cols),z=8+Math.random()*.6,s=Math.min(w,h)*.9/z;return {x:(sx-w/2)/s,y:(sy-h*.54)/s,z,shape:0,good:true,number:i+1,phase:Math.random()*6,index:i}})}
 function message(text){const e=document.querySelector('#hint');if(e)e.textContent=text}
 function newRound(){flips=[];inputIndex=0;turn=0;next=1;phase='answer';
  if(id==='sequence'){objects=layout([6,8,9][d]);const nums=shuffle(objects.map((_,i)=>i+1));objects.forEach((o,i)=>o.label=nums[i]);message('按顺序点击 · 下一个 1')}
  if(id==='odd'){objects=layout([6,9,12][d],d===2?4:3);sample=rnd(4);const different=rnd(objects.length);objects.forEach((o,i)=>{o.shape=i===different?(sample+1+rnd(3))%4:sample;o.target=i===different;o.label=''});message('找到形状不同的那个')}
  if(id==='memory'){const pairs=[3,4,6][d],values=shuffle(Array.from({length:pairs*2},(_,i)=>i%pairs));objects=layout(pairs*2,pairs===3?3:4);objects.forEach((o,i)=>{o.value=values[i];o.card=true;o.label='?';o.matched=false;o.revealed=false});message('翻开两张 · 找相同图案')}
  if(id==='signal'){objects=[];phase='waiting';phaseEnd=elapsed+1;message('青色菱形才点 · 橙色方块等待')}
  if(id==='orbit'){objects=layout([4,5,6][d],3);const count=[1,2,2][d];objects.forEach((o,i)=>{o.target=i<count;o.shape=2;o.label='';o.x=Math.cos(i*2*Math.PI/objects.length)*2;o.y=Math.sin(i*2*Math.PI/objects.length)*1.1;o.baseX=o.x;o.baseY=o.y});phase='show';phaseEnd=elapsed+2.5;message('记住带白圈的星球')}
  if(id==='direction'){objects=[{x:0,y:0,z:7,shape:0,label:['→','↓','←','↑'][sample=rnd(4)]}];message('观察中央箭头 · 选择方向')}
  if(id==='match'){sample=rnd(4);objects=layout(4,2);const types=shuffle([0,1,2,3]);objects.forEach((o,i)=>{o.shape=types[i];o.label='';o.target=o.shape===sample});message('上方是样本 · 选择相同形状')}
  if(id==='path'){objects=layout(9,3);objects.forEach(o=>{o.card=true;o.label='';o.revealed=false});pattern=Array.from({length:[3,4,5][d]},()=>rnd(9));phase='showpath';phaseEnd=elapsed+.5;turn=-1;message('先看亮起顺序，暂时不要点')}
 }
 function start(mode,level,seconds,done){id=mode;d=Math.max(0,Math.min(2,level));duration=seconds;callback=done;active=true;ambient=false;paused=false;elapsed=hits=errors=missed=score=rounds=inTime=spawn=0;objects=[];pointer={x:-999,y:-999};goal=id==='memory'?[3,4,6][d]:id==='sequence'?[6,8,9][d]:id==='orbit'?[3,5,7][d]:id==='path'?[6,8,10][d]:[6,9,12][d];if(id==='collect'){message('收集青色晶体，橙色方块不要点')}else if(id==='follow'){objects=[{x:0,y:0,z:7,shape:0,label:''}];message('移动鼠标或拖动手指，跟随星体')}else newRound();last=performance.now()}
 function stop(){active=false;ambient=false;paused=false;objects=[]}
 function pause(force){if(!active)return;paused=force===true?true:!paused;const b=document.querySelector('#pause');if(b)b.textContent=paused?'继续':'暂停';message(paused?'已暂停 · 准备好后继续':'继续挑战 · 按本关规则操作');last=performance.now()}
 function finish(){if(!active)return;active=false;const result={id,d,hits,errors,missed,rounds,score,seconds:elapsed,goal,ratio:elapsed?inTime/elapsed:0};callback?.(result)}
 function correct(){hits++;score+=10}
 function wrong(){errors++;score=Math.max(0,score-3)}
 function inputObject(o){if(!active||paused)return;
  if(id==='collect'){if(!o){wrong();return}o.good?correct():wrong();objects=objects.filter(x=>x!==o)}
  else if(id==='sequence'){if(!o||o.label!==next){wrong();return}correct();o.done=true;next++;message('下一个 '+next);if(next>objects.length){rounds++;newRound()}}
  else if(id==='odd'||id==='match'){if(!o)return;if(o.target){correct();rounds++;newRound()}else wrong()}
  else if(id==='memory'){if(!o||phase==='mismatch'||o.matched||o.revealed)return;o.revealed=true;flips.push(o);if(flips.length===2){if(flips[0].value===flips[1].value){flips.forEach(x=>x.matched=true);correct();flips=[];if(objects.every(x=>x.matched)){rounds++;finish()}}else{wrong();phase='mismatch';phaseEnd=elapsed+.85}}}
  else if(id==='signal'){if(phase==='signal'&&o){if(o.good)correct();else wrong();phase='waiting';phaseEnd=elapsed+.6;objects=[]}else wrong()}
  else if(id==='orbit'){if(phase!=='answer'||!o||o.done)return;o.done=true;if(o.target)correct();else wrong();if(objects.filter(x=>x.done).length===[1,2,2][d]){missed+=objects.filter(x=>x.target&&!x.done).length;rounds++;newRound()}}
  else if(id==='path'){if(phase!=='replay'||!o)return;if(o.index===pattern[inputIndex]){correct();inputIndex++;message('已记对 '+inputIndex+' / '+pattern.length);if(inputIndex===pattern.length){rounds++;newRound()}}else{wrong();newRound()}}
 }
 function direction(a){if(active&&!paused&&id==='direction'){a===sample?correct():wrong();newRound()}}
 const move=e=>pointer={x:e.clientX,y:e.clientY};canvas.addEventListener('pointermove',move);canvas.addEventListener('pointerdown',e=>{move(e);if(id==='follow'){canvas.setPointerCapture?.(e.pointerId);return}const o=[...objects].filter(o=>!o.done&&!o.matched).sort((a,b)=>a.z-b.z).find(o=>{const p=project(o);return Math.hypot(e.clientX-p.x,e.clientY-p.y)<Math.max(26,Math.min(38,p.s*.53))});inputObject(o)});canvas.addEventListener('pointerup',e=>{if(e.pointerType==='touch')pointer={x:-999,y:-999}});canvas.addEventListener('pointercancel',()=>pointer={x:-999,y:-999});
 function draw(o,preview=false){if(o.done||o.matched)return;const p=project(o),r=Math.max(24,Math.min(38,p.s*.48)),color=o.good===false?'#ffbd85':palette[o.shape||0];ctx.save();ctx.translate(p.x,p.y);ctx.shadowColor=color;ctx.shadowBlur=preview?30:8;ctx.lineWidth=1.5;ctx.strokeStyle='#ffffff90';ctx.fillStyle=color;
  if(o.card){const lit=o.revealed||(phase==='showpath'&&pattern[turn]===o.index&&elapsed<phaseEnd-.2);ctx.fillStyle=lit?'#9debd5':'#263a59';ctx.beginPath();if(ctx.roundRect)ctx.roundRect(-r,-r,r*2,r*2,10);else ctx.rect(-r,-r,r*2,r*2);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#f8fffc';ctx.font='bold 26px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(o.revealed?glyphs[o.value]:o.label||'',0,1);ctx.restore();return}
  const shape=o.shape||0;if(shape===2){const g=ctx.createRadialGradient(-r*.3,-r*.4,1,0,0,r);g.addColorStop(0,'#ecf9ff');g.addColorStop(.4,color);g.addColorStop(1,'#394378');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,0,r,0,Math.PI*2);ctx.fill()}else{const angle=Math.sin(t*.4+(o.phase||0))*.13;ctx.rotate(angle);ctx.beginPath();const points=shape===1?[[-r,-r*.65],[r*.45,-r],[r,r*.55],[-r*.5,r]]:shape===3?[[0,-r],[r,r*.7],[-r,r*.7]]:[[0,-r],[r*.78,0],[0,r],[-r*.78,0]];points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#ffffff35';ctx.beginPath();ctx.moveTo(0,-r);ctx.lineTo(0,0);ctx.lineTo(r*.7,shape===1?-r*.5:0);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(0,r*.9);ctx.stroke();ctx.rotate(-angle)}
  if(id==='orbit'&&phase==='show'&&o.target){ctx.beginPath();ctx.arc(0,0,r+8,0,Math.PI*2);ctx.lineWidth=3;ctx.strokeStyle='white';ctx.stroke()}
  ctx.shadowBlur=0;ctx.fillStyle='#122b3e';ctx.font='bold 24px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';if(o.label)ctx.fillText(o.label,0,0);ctx.restore();
 }
 function step(dt){elapsed+=dt;if(elapsed>=duration){elapsed=duration;finish();return}if(id==='collect'){spawn-=dt;if(spawn<=0){const good=Math.random()>.28;objects.push({x:(Math.random()-.5)*4.3,y:(Math.random()-.5)*2,z:19,good,shape:good?0:1,phase:Math.random()*6});spawn=[1.05,.85,.65][d]}objects.forEach(o=>o.z-=dt*[3,4,5][d]);objects=objects.filter(o=>{if(o.z<4){if(o.good)missed++;return false}return true})}
  if(id==='follow'){const o=objects[0];o.x=Math.sin(elapsed*[.5,.65,.8][d])*2;o.y=Math.sin(elapsed*.75)*.85;const p=project(o);if(Math.hypot(pointer.x-p.x,pointer.y-p.y)<Math.max(28,Math.min(42,p.s*.6)))inTime+=dt}
  if(id==='memory'&&phase==='mismatch'&&elapsed>=phaseEnd){flips.forEach(o=>o.revealed=false);flips=[];phase='answer'}
  if(id==='signal'&&elapsed>=phaseEnd){if(phase==='signal'){if(objects[0]?.good)missed++;objects=[];phase='waiting';phaseEnd=elapsed+.6}else{const good=Math.random()>.35;objects=[{x:0,y:0,z:7,good,shape:good?0:1,label:''}];phase='signal';phaseEnd=elapsed+[1.8,1.3,1][d]}}
  if(id==='orbit'){if(phase==='show'&&elapsed>=phaseEnd){phase='moving';phaseEnd=elapsed+[3.5,4.5,5.5][d];message('跟随它们的位置，暂时不要点')}if(phase==='moving'){objects.forEach((o,i)=>{const a=(elapsed-(phaseEnd-[3.5,4.5,5.5][d]))*[.55,.7,.9][d]+i*2*Math.PI/objects.length;o.x=Math.cos(a)*2;o.y=Math.sin(a)*1.1});if(elapsed>=phaseEnd){phase='answer';message('现在找回刚才带白圈的 '+[1,2,2][d]+' 颗星球')}}}
  if(id==='path'&&phase==='showpath'&&elapsed>=phaseEnd){turn++;phaseEnd=elapsed+[.85,.7,.6][d];if(turn>=pattern.length){phase='replay';message('轮到你了 · 按顺序点击')}}
 }
 function frame(now){const dt=Math.min(Math.max((now-last)/1000,0),.1);last=now;if(active&&!paused||ambient)t+=dt;ctx.clearRect(0,0,w,h);const g=ctx.createLinearGradient(0,0,w,h);g.addColorStop(0,'#09162b');g.addColorStop(1,'#142d43');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);stars.forEach(s=>{ctx.fillStyle='#b9ddeb70';ctx.beginPath();ctx.arc(s.x*w,s.y*h,s.r,0,Math.PI*2);ctx.fill()});if(active||ambient){ctx.strokeStyle='#78dbc411';for(let z=6;z<50;z+=5){const r=Math.min(w,h)*3/(z-(t*.3%4));ctx.beginPath();ctx.ellipse(w*.5,h*.53,r*2,r,0,0,Math.PI*2);ctx.stroke()}}
  if(active){if(!paused)step(dt);if(active){objects.forEach(o=>draw(o));if(id==='match'){const s=Math.min(w,h)*.9/7;draw({x:0,y:(178-h*.54)/s,z:7,shape:sample,label:''},true)}if(id==='follow'){ctx.strokeStyle='#f4fffd';ctx.beginPath();ctx.arc(pointer.x,pointer.y,12,0,Math.PI*2);ctx.stroke()}const gs=document.querySelector('#gameScore'),gt=document.querySelector('#gameTime');if(gs)gs.textContent=id==='follow'?'跟随 '+Math.round((elapsed?inTime/elapsed:0)*100)+'%':'能量 '+score+' · 正确 '+hits;if(gt)gt.textContent=Math.ceil(duration-elapsed)+' 秒'}}else if(ambient&&w>800){draw({x:3,y:-.3,z:7,shape:2,label:''},true);draw({x:2,y:1.2,z:8,shape:0,label:''},true)}requestAnimationFrame(frame)}requestAnimationFrame(frame);
 return{start,stop,pause,finish,direction,setAmbient:v=>ambient=v};
})();

